### ISSUE TITLE
Thank you for your library. which files would i use for android development?

### ISSUE THREAD

**Issue by behsaman** [hughperkins/jeigen#9]

**Comment by hughperkins** [comment]
Android .... hmmm.... well... jeigen comprises two parts:
- java classes, portable
- native library, needs to be built for each platform

If portability is more important than raw performance, you might consider a java-only library.  It might be half as fast, especially for matrix multiplications, but it will be significantly more portable, easier to package and install.

Otherwise... you will need to build the native library for your target platform somehow.  You can take a look at the CMakeLists.txt, in the [src/native](src/native) directory, and try building this (using cmake + some kind of c compiler).

**Comment by hughperkins** [comment]
Note: I googled a bit, for 'android cmake', and came up with the following links, for building for android, using cmake:
- https://code.google.com/archive/p/android-cmake/
- http://android-cmake.googlecode.com/hg/documentation.html
- http://stackoverflow.com/questions/19343797/building-a-toolchain-with-cmake-to-cross-compile-for-android
